# Generated by Django 6.0.1 on 2026-01-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerRoomEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('equipment_touched', models.TextField(blank=True)),
                ('supervisor', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gridapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FieldActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substation', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time_out', models.TimeField()),
                ('time_returned', models.TimeField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('materials_used', models.TextField(blank=True)),
                ('supervisor_approval', models.CharField(blank=True, max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gridapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date_reported', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=50)),
                ('status', models.CharField(default='open', max_length=50)),
                ('resolution_remarks', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gridapp.staff')),
            ],
        ),
    ]
