# Generated by Django 6.0.1 on 2026-02-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_faultreport_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_email', models.EmailField(max_length=254)),
                ('feedback_text', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('fault', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='gridapp.faultreport')),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
