# Generated by Django 6.0.1 on 2026-02-09 21:07

import gridapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0003_faultfeedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faultreport',
            options={'ordering': ['-date_reported']},
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[gridapp.models.validate_file_size, gridapp.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='status',
            field=models.CharField(db_index=True, default='open', max_length=50),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['-date_reported'], name='gridapp_fau_date_re_b1ceca_idx'),
        ),
        migrations.AddIndex(
            model_name='faultreport',
            index=models.Index(fields=['status', '-date_reported'], name='gridapp_fau_status_6b47a0_idx'),
        ),
    ]
