# Generated by Django 6.0.1 on 2026-02-11 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0004_alter_faultreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRoomVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
