# Generated by Django 6.0.1 on 2026-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0005_serverroomvisitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverroomvisitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('ATTACHMENT_DELETE', 'Attachment Deleted'), ('BULK_DELETE', 'Bulk Delete'), ('BULK_UPDATE', 'Bulk Update')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField()),
                ('user', models.CharField(default='system', max_length=200)),
                ('changes', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='gridapp_aud_model_n_c9d9ea_idx'), models.Index(fields=['-timestamp'], name='gridapp_aud_timesta_b16ae3_idx'), models.Index(fields=['user', '-timestamp'], name='gridapp_aud_user_23b015_idx')],
            },
        ),
    ]
